feat: Implement new features

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -1,12 +1,11 @@
-@echo off
+#!/bin/sh
 
-set commit_message_file=%1
+commit_message_file=$1
 
-rem Check if the commit message contains tags like "feat", "fix", "refactor", etc.
-findstr /I /R "^(fix^|refactor^|chore^|docs^|style^|test^)(\(.\+\))?!?:" "%commit_message_file%" > nul
-if %errorlevel% == 0 (
-    exit 0  rem Commit message contains valid tags
-) else (
-    echo Error: Commit message must start with a valid type tag (feat, fix, refactor, etc.)
-    exit 1  rem Exit with non-zero status to reject the commit
-)
+# Check if the commit message contains tags like "feat", "fix", "refactor", etc.
+if grep -iqE '^(feat|fix|refactor|chore|docs|style|test)(\(.+\))?!?:' "$commit_message_file"; then
+  exit 0  # Commit message contains valid tags
+else
+  echo "Error: Commit message must start with a valid type tag (feat, fix, refactor, etc.)"
+  exit 1  # Exit with non-zero status to reject the commit
+fi
